### ISSUE TITLE
Sort tags alphabetically ?

### ISSUE THREAD

**Issue by it-praktyk** [5t111111/middleman-blog-drops-template#13]
Hi,
is it possible to sort tags alphabetically ?

[On my blog](https://blog.it-praktyk.pl/tags/) tags are added in the articles orders, the next how were listed in the article.

**Comment by 5t111111** [comment]
@it-praktyk ATM it's impossible to sort tags alphabetically, but the fix for changing sort order is quite easy.

You can add `sort` to the template for tags (`source/tags.html.slim`) like the following then tags will be sorted alphabetically.

```slim
h1
  | Tags
ul
  - blog.tags.sort.each do |(tag, articles)|
    li.tag-list
      a href="#{tag_path(tag)}"
        .tag-label
          | #{tag} (#{articles.size})
```

Since I also think this behavior is more preferable, I'll update the above file later.

**Comment by it-praktyk** [comment]
Thank you :-)

**Comment by 5t111111** [comment]
Closed via https://github.com/5t111111/middleman-blog-drops-template/commit/238bd3c30a401ca0536714df5d735f16591e5ce6
