### ISSUE TITLE
The missing dependency for compass-mixins ?

### ISSUE THREAD

**Issue by it-praktyk** [5t111111/middleman-blog-drops-template#5]
Hi,
in the file build/stylesheets/site i see error like below

`/*
Error: File to import not found or unreadable: compass-mixins/lib/compass/reset.
        on line 1 of /home/<user>/my-blog/source/stylesheets/site.scss

1: @import "compass-mixins/lib/compass/reset";
2: @import "compass-mixins/lib/compass";
3: 
4: @import 'breakpoint-sass/stylesheets/breakpoint';
5: 
6: @import url(http://fonts.googleapis.com/css?family=Lato:400,700);

Backtrace:
/home/<user>/my-blog/source/stylesheets/site.scss:1
/usr/local/share/gems/gems/sass-3.4.21/lib/sass/tree/import_node.rb:67:in `rescue in import'`

How can I resolve it? Probably I need download and install additional gem based on a code from [https://github.com/Igosuki/compass-mixins](https://github.com/Igosuki/compass-mixins) but I'm not sure.

I've created my blog project using a command

`middleman init -T 5t111111/middleman-blog-drops-template#upgrade-to-v4 my-blog`

Could you help me?

BTW, thank you for your work on drops-template. Good work!

**Comment by 5t111111** [comment]
Thank you for reporting an issue :smile: 

Libraries like `compass-mixins/lib/compass/reset` are installed in `node_modules` via `npm install`, but sass can't find them because it doesn't know their paths.

However, practically it doesn't matter because sass files (e.g. site.scss) are handled by webpack so that `site.scss` are correctly loaded.

I've added excluding option to `config.rb` so that `build/stylesheets/` no longer generated. Please checkout the latest version. 

> middleman init -T 5t111111/middleman-blog-drops-template#upgrade-to-v4 my-blog

Since now `upgrade-to-v4` branch is merged into `master`, you don't have to point `#upgrade-to-v4` anymore.

**Comment by it-praktyk** [comment]
Hi :-)

Thank you for your answer.

Even after creating the new blog project I see in the build directory the stylesheets subfolder with the site file.

Can I ignore that the file exists and contains errors?

**Comment by 5t111111** [comment]
@it-praktyk Yes, you can just ignore the stylesheets directory with the corrupted site file.

But before that, please make sure you are using `master` branch instead of `upgrade-to-v4`. `upgrade-to-v4` is no longer maintained.

```
middleman init -T 5t111111/middleman-blog-drops-template my-blog
```

**Comment by it-praktyk** [comment]
OK, my fault - I've used command from the history this time.

Thank you.
