### ISSUE TITLE
Updating Markdown processor to Kramdown

### ISSUE THREAD

**Issue by huideyeren** [5t111111/middleman-blog-drops-template#8]
## Overview

https://help.github.com/articles/updating-your-markdown-processor-to-kramdown/

GitHub announced starting May 1st, 2016, GitHub Pages will only support kramdown.

I tested updating Markdown processor to Kramdown.

## Problems

The problem is as follows:

- I could not use Superscripts

## Reference

[My blog's article using drops template with Kramdown](http://huideyeren.info/2016/03/16/changed-markdown-engine-to-kramdown/)

**Comment by 5t111111** [comment]
As a matter of fact, the HEAD of the master branch is already changed to use kramdown rather than redcarpet (see https://github.com/5t111111/middleman-blog-drops-template/commit/6987442395dd521511013734c4aba3718e2f33a0) .

So if you are ok to upgrade Middleman v4 and use the latest version of this template, you don't have to worry about migrating redcarpet to kramdown. [This comment](https://github.com/5t111111/middleman-blog-drops-template/issues/1#issuecomment-174825857) may help you when you have problem when upgrading.

Thanks for reporting an issue anyway :wink:
